// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4R1mwBEyeSX2rNwOWIDsNE_hJtgcvwrY',
    appId: '1:357454320356:web:3f8c6df705a50aa2b812f1',
    messagingSenderId: '357454320356',
    projectId: 'momento-b23c0',
    authDomain: 'momento-b23c0.firebaseapp.com',
    storageBucket: 'momento-b23c0.firebasestorage.app',
    measurementId: 'G-50T3ETMY9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCItKuJpA-hceHEPIy9A4QRgpR5YSmgsUA',
    appId: '1:357454320356:android:073e2256b5114537b812f1',
    messagingSenderId: '357454320356',
    projectId: 'momento-b23c0',
    storageBucket: 'momento-b23c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoGnfj-Cvo_cgPT4OatSBEeKl5dK1NoWA',
    appId: '1:357454320356:ios:3d5d35618ab23ae7b812f1',
    messagingSenderId: '357454320356',
    projectId: 'momento-b23c0',
    storageBucket: 'momento-b23c0.firebasestorage.app',
    iosBundleId: 'community.momento.app',
  );
}
